name: CI of mc-rtc-superbuild

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  schedule:
    # Run on Sunday, Tuesday and Thursday nights
    - cron: '0 22 * * 0,1,4'

jobs:
  run:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install system dependencies
      shell: bash
      run: |
        mkdir -p ${TMPDIR-/tmp}/build-mc-rtc
        cmake -S ${GITHUB_WORKSPACE} -B ${TMPDIR-/tmp}/build-mc-rtc -DCMAKE_BUILD_TYPE=RelWithDebInfo -DUPDATE_ALL=OFF
    - name: Install mc_rtc and related projects
      shell: bash
      run: |
        cmake --build ${TMPDIR-/tmp}/build-mc-rtc --config RelWithDebInfo
